/* eslint-disable */
// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// To change this file, edit the core spec it derives from and rerun `pnpm codegen`.

import { useBehavior } from "@render-experiment/behavior-react";
import {
  connectTooltip,
  tooltipBehavior,
  type TooltipApi,
  type TooltipContext as TooltipBehaviorContext,
  type TooltipProps,
  type TooltipState,
} from "@render-experiment/tooltip-core";

/** Wire the core behavior to React and return the connect() API. */
export function useTooltipApi(props: TooltipProps): TooltipApi {
  const behavior = useBehavior<TooltipBehaviorContext, TooltipProps>(
    tooltipBehavior,
    props,
  );
  return connectTooltip(
    behavior.getState() as TooltipState,
    behavior.getContext(),
    behavior.getProps(),
    behavior.send,
  );
}
