/* eslint-disable */
// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// To change this file, edit the core spec it derives from and rerun `pnpm codegen`.

import { styled } from "@render-experiment/style-react";

// Source: core/tooltip/src/styles.ts → content
export const Content = styled(
  "div",
  {
  "position": "absolute",
  "pointerEvents": "auto",
  "background": "#111",
  "color": "#fff",
  "paddingTop": 6,
  "paddingBottom": 6,
  "paddingLeft": 10,
  "paddingRight": 10,
  "borderRadius": 4,
  "fontSize": 13,
  "variants": {
    "side": {
      "top": {
        "bottom": "100%"
      },
      "bottom": {
        "top": "100%"
      },
      "left": {
        "right": "100%"
      },
      "right": {
        "left": "100%"
      }
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "side": "bottom"
  }
} as any,
);

// Source: core/tooltip/src/styles.ts → positioner
export const Positioner = styled(
  "div",
  {
  "position": "fixed",
  "width": 0,
  "height": 0,
  "variants": {
    "anchored": {
      "true": {
        "visibility": "visible"
      },
      "false": {
        "visibility": "hidden"
      }
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "anchored": "false"
  }
} as any,
);
