/* eslint-disable */
// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// To change this file, edit the core spec it derives from and rerun `pnpm codegen`.

import { withAdapter } from "@render-experiment/machine-core";
import { createMachineRuntime, type MachineRuntime } from "@render-experiment/machine-pixi";
import {
  connectTooltip,
  tooltipMachine,
  type TooltipApi,
  type TooltipContext as TooltipMachineContext,
  type TooltipProps,
  type TooltipState,
} from "@render-experiment/tooltip-core";
import { tooltipAdapter } from "./adapter";

const tooltipMachineWithAdapter = withAdapter(tooltipMachine, tooltipAdapter);

/**
 * Pixi version: not a hook (no React). Returns a runtime + a getApi() that
 * re-derives the connect() output on demand. Consumer subscribes to
 * runtime to know when to re-derive.
 */
export interface TooltipBridge {
  runtime: MachineRuntime<TooltipMachineContext, TooltipProps>;
  /** Latest connect() output for the current state. */
  getApi: () => TooltipApi;
}

export function createTooltipBridge(props: TooltipProps): TooltipBridge {
  const runtime = createMachineRuntime<TooltipMachineContext, TooltipProps>(
    tooltipMachineWithAdapter,
    props,
  );
  const { machine } = runtime;
  return {
    runtime,
    getApi: () =>
      connectTooltip({
        state: machine.getState() as TooltipState,
        context: machine.getContext(),
        props: machine.getProps(),
        send: machine.send,
      })(),
  };
}
