/* eslint-disable */
// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// To change this file, edit the core spec it derives from and rerun `pnpm codegen`.

import { styled } from "@render-experiment/style-engine-pixi";

// Source: core/components/tooltip/src/elements → content (primitive: graphics)
export const Content = styled("graphics", {
  "base": {
    "position": "absolute",
    "pointerEvents": "auto",
    "background": 1118481,
    "color": 16777215,
    "paddingY": 6,
    "paddingX": 10,
    "borderRadius": 4,
    "fontSize": 13
  },
  "variants": {
    "side": {
      "top": {
        "bottom": "100%"
      },
      "bottom": {
        "top": "100%"
      },
      "left": {
        "right": "100%"
      },
      "right": {
        "left": "100%"
      }
    },
    "red": {
      "true": {
        "background": 12597547
      },
      "false": {}
    },
    "blue": {
      "true": {
        "background": 65280
      },
      "false": {}
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "side": "bottom",
    "red": "false"
  }
});

// Source: core/components/tooltip/src/elements → positioner (primitive: container)
export const Positioner = styled("container", {
  "base": {
    "position": "fixed",
    "width": 0,
    "height": 0
  },
  "variants": {
    "anchored": {
      "true": {
        "visibility": "visible"
      },
      "false": {
        "visibility": "hidden"
      }
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "anchored": "false"
  }
});
