/* eslint-disable */
// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// To change this file, edit the core spec it derives from and rerun `pnpm codegen`.

import { withAdapter } from "@render-experiment/machine-core";
import { useMachine } from "@render-experiment/machine-native";
import {
  connectDropdownMenu,
  dropdownMenuMachine,
  type DropdownMenuApi,
  type DropdownMenuContext as DropdownMenuMachineContext,
  type DropdownMenuProps,
  type DropdownMenuState,
} from "@render-experiment/dropdown-menu-core";
import { dropdownMenuAdapter } from "./adapter";

const dropdownMenuMachineWithAdapter = withAdapter(dropdownMenuMachine, dropdownMenuAdapter);

/** Wire the core machine to native and return the connect() API. */
export function useDropdownMenuApi(props: DropdownMenuProps): DropdownMenuApi {
  const machine = useMachine<DropdownMenuMachineContext, DropdownMenuProps>(
    dropdownMenuMachineWithAdapter,
    props,
  );
  return connectDropdownMenu({
    state: machine.getState() as DropdownMenuState,
    context: machine.getContext(),
    props: machine.getProps(),
    send: machine.send,
  })();
}
