/* eslint-disable */
// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// To change this file, edit the core spec it derives from and rerun `pnpm codegen`.

import { resolveStyle, type TranslatedNativeStyle } from "@render-experiment/style-engine-native";

// Source: core/components/dropdown-menu/src/styles.ts → content
export const content: TranslatedNativeStyle = {
  "base": {
    "position": "absolute",
    "backgroundColor": "#1f2937",
    "color": "#fff",
    "borderRadius": 6,
    "paddingVertical": 4,
    "paddingHorizontal": 0,
    "fontSize": 13,
    "minWidth": 180,
    "boxShadow": "0 10px 30px rgba(0,0,0,0.25), 0 2px 8px rgba(0,0,0,0.15)"
  },
  "variants": {
    "side": {
      "top": {
        "bottom": "100%"
      },
      "bottom": {
        "top": "100%"
      },
      "left": {
        "right": "100%"
      },
      "right": {
        "left": "100%"
      }
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "side": "bottom"
  }
};

export function resolveContent(selections: Record<string, string> = {}) {
  return resolveStyle(content, selections);
}

// Source: core/components/dropdown-menu/src/styles.ts → group
export const group: TranslatedNativeStyle = {
  "base": {
    "display": "block"
  },
  "variants": {},
  "compoundVariants": [],
  "defaultVariants": {}
};

export function resolveGroup(selections: Record<string, string> = {}) {
  return resolveStyle(group, selections);
}

// Source: core/components/dropdown-menu/src/styles.ts → item
export const item: TranslatedNativeStyle = {
  "base": {
    "display": "flex",
    "alignItems": "center",
    "paddingVertical": 6,
    "paddingHorizontal": 12,
    "outline": "none"
  },
  "variants": {
    "highlighted": {
      "true": {
        "backgroundColor": "#374151"
      },
      "false": {
        "backgroundColor": "transparent"
      }
    },
    "disabled": {
      "true": {
        "opacity": 0.5
      },
      "false": {}
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "highlighted": "false",
    "disabled": "false"
  }
};

export function resolveItem(selections: Record<string, string> = {}) {
  return resolveStyle(item, selections);
}

// Source: core/components/dropdown-menu/src/styles.ts → label
export const label: TranslatedNativeStyle = {
  "base": {
    "paddingVertical": 6,
    "paddingHorizontal": 12,
    "fontSize": 11,
    "fontWeight": 600,
    "color": "#9ca3af",
    "textTransform": "uppercase",
    "letterSpacing": "0.05em"
  },
  "variants": {},
  "compoundVariants": [],
  "defaultVariants": {}
};

export function resolveLabel(selections: Record<string, string> = {}) {
  return resolveStyle(label, selections);
}

// Source: core/components/dropdown-menu/src/styles.ts → positioner
export const positioner: TranslatedNativeStyle = {
  "base": {
    "position": "fixed",
    "width": 0,
    "height": 0
  },
  "variants": {
    "anchored": {
      "true": {},
      "false": {}
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "anchored": "false"
  }
};

export function resolvePositioner(selections: Record<string, string> = {}) {
  return resolveStyle(positioner, selections);
}

// Source: core/components/dropdown-menu/src/styles.ts → separator
export const separator: TranslatedNativeStyle = {
  "base": {
    "height": 1,
    "marginVertical": 4,
    "marginHorizontal": 0,
    "backgroundColor": "#374151"
  },
  "variants": {},
  "compoundVariants": [],
  "defaultVariants": {}
};

export function resolveSeparator(selections: Record<string, string> = {}) {
  return resolveStyle(separator, selections);
}
