/* eslint-disable */
// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// To change this file, edit the core spec it derives from and rerun `pnpm codegen`.

import { styled } from "@render-experiment/style-engine-react";

// Source: core/components/dropdown-menu/src/elements → content
export const Content = styled(
  "div",
  {
  "position": "absolute",
  "pointerEvents": "auto",
  "background": "#1f2937",
  "color": "#fff",
  "borderRadius": 6,
  "paddingTop": 4,
  "paddingBottom": 4,
  "paddingLeft": 0,
  "paddingRight": 0,
  "fontSize": 13,
  "minWidth": 180,
  "boxShadow": "0 10px 30px rgba(0,0,0,0.25), 0 2px 8px rgba(0,0,0,0.15)",
  "variants": {
    "side": {
      "top": {
        "bottom": "100%"
      },
      "bottom": {
        "top": "100%"
      },
      "left": {
        "right": "100%"
      },
      "right": {
        "left": "100%"
      }
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "side": "bottom"
  }
} as any,
);

// Source: core/components/dropdown-menu/src/elements → group
export const Group = styled(
  "div",
  {
  "display": "block",
  "variants": {},
  "compoundVariants": [],
  "defaultVariants": {}
} as any,
);

// Source: core/components/dropdown-menu/src/elements → item
export const Item = styled(
  "div",
  {
  "display": "flex",
  "alignItems": "center",
  "paddingTop": 6,
  "paddingBottom": 6,
  "paddingLeft": 12,
  "paddingRight": 12,
  "cursor": "default",
  "userSelect": "none",
  "outline": "none",
  "variants": {
    "highlighted": {
      "true": {
        "background": "#374151"
      },
      "false": {
        "background": "transparent"
      }
    },
    "disabled": {
      "true": {
        "opacity": 0.5,
        "cursor": "not-allowed"
      },
      "false": {}
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "highlighted": "false",
    "disabled": "false"
  }
} as any,
);

// Source: core/components/dropdown-menu/src/elements → label
export const Label = styled(
  "div",
  {
  "paddingTop": 6,
  "paddingBottom": 6,
  "paddingLeft": 12,
  "paddingRight": 12,
  "fontSize": 11,
  "fontWeight": 600,
  "color": "#9ca3af",
  "textTransform": "uppercase",
  "letterSpacing": "0.05em",
  "variants": {},
  "compoundVariants": [],
  "defaultVariants": {}
} as any,
);

// Source: core/components/dropdown-menu/src/elements → positioner
export const Positioner = styled(
  "div",
  {
  "position": "fixed",
  "width": 0,
  "height": 0,
  "variants": {
    "anchored": {
      "true": {
        "visibility": "visible"
      },
      "false": {
        "visibility": "hidden"
      }
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "anchored": "false"
  }
} as any,
);

// Source: core/components/dropdown-menu/src/elements → separator
export const Separator = styled(
  "div",
  {
  "height": 1,
  "marginY": 4,
  "marginX": 0,
  "background": "#374151",
  "variants": {},
  "compoundVariants": [],
  "defaultVariants": {}
} as any,
);
