/* eslint-disable */
// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// To change this file, edit the core spec it derives from and rerun `pnpm codegen`.

import { resolveStyle, type TranslatedNativeStyle } from "@render-experiment/style-engine-native";

// Source: core/components/tooltip/src/styles.ts → content
export const content: TranslatedNativeStyle = {
  "base": {
    "position": "absolute",
    "backgroundColor": "#111",
    "color": "#fff",
    "paddingVertical": 6,
    "paddingHorizontal": 10,
    "borderRadius": 4,
    "fontSize": 13
  },
  "variants": {
    "side": {
      "top": {
        "bottom": "100%"
      },
      "bottom": {
        "top": "100%"
      },
      "left": {
        "right": "100%"
      },
      "right": {
        "left": "100%"
      }
    },
    "red": {
      "true": {
        "backgroundColor": "#c0392b"
      },
      "false": {}
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "side": "bottom",
    "red": "false"
  }
};

export function resolveContent(selections: Record<string, string> = {}) {
  return resolveStyle(content, selections);
}

// Source: core/components/tooltip/src/styles.ts → positioner
export const positioner: TranslatedNativeStyle = {
  "base": {
    "position": "fixed",
    "width": 0,
    "height": 0
  },
  "variants": {
    "anchored": {
      "true": {},
      "false": {}
    }
  },
  "compoundVariants": [],
  "defaultVariants": {
    "anchored": "false"
  }
};

export function resolvePositioner(selections: Record<string, string> = {}) {
  return resolveStyle(positioner, selections);
}
